version: '2'

services:
  masternode :
    image : hadoop_single_node:ver10
    container_name : masternode
    hostname : masternode
    user : root
    volumes:
      - single_node_volume:/usr/local/hadoop/hdfs
    environment : 
      - HADOOP_HOME=/usr/local/hadoop
    networks : 
      - hadoop-net
    ports : 
      - "9870:9870"
      - "8088:8088"
      - "9000:9000" 
      - "9864:9864"
    command : ["/bin/bash", "-c", "service ssh start && $HADOOP_HOME/sbin/start-dfs.sh && $HADOOP_HOME/sbin/start-yarn.sh "]

  workernode1 :
    image : hadoop_single_node:ver10
    container_name : workernode1
    hostname : workernode1
    user : root
    volumes:
      - single_node_volume:/usr/local/hadoop/hdfs
    environment : 
      - HADOOP_HOME=/usr/local/hadoop
    networks : 
      - hadoop-net
    command : ["/bin/bash", "-c", "service ssh start "]

  workernode2 :
    image : hadoop_single_node:ver10
    container_name : workernode2
    hostname : workernode2
    user : root
    volumes:
      - single_node_volume:/usr/local/hadoop/hdfs
    environment : 
      - HADOOP_HOME=/usr/local/hadoop
    networks : 
      - hadoop-net
    command : ["/bin/bash", "-c", "service ssh start "]

networks:
  hadoop-net:
    driver: bridge

volumes:
  single_node_volume: